[world]
name = "Dojo intro"
description = "A simple intro to Dojo."
seed = "dojo_intro"

[namespace]
default = "di"

[env]
rpc_url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_9/oJTjnNCsJEOqYv3MMtrtT6LUFhwcW9pR"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[writers]
"di" = ["di-actions", "di-game_system"]
